from BaseClasses import Location
from .Items import BASE_ID

class KSAWLocation(Location):
    game: str = "Kirby ~ Soft & Wet"

# Stage completion locations
fish_count_locations = [f"Obtained Fish #{i}" for i in range(1, 667)]

fish_locations = [
    "Blipper_Caught",
    "Slippy_Caught",
    "Glunk_Caught",
    "Diving Gordo_Caught",
    "Leap_Caught",
    "Gusso_Caught",
    "Joe_Caught",
    "Pacto_Caught",
    "Squishy_Caught",
    "Flotzo_Caught",
    "Peezer_Caught",
    "Tortletummy_Caught",
    "Stickle_Caught",
    "Squister_Caught",
    "Slugoo_Caught",
    "Elebli_Caught",
    "Blish_Caught",
    "King Eelongo_Caught",
    "Acro_Caught",
    "Fatty Whale_Caught",
    "Mini Gobbler_Caught",
    "Gobbler_Caught",
    "Kine_Caught",
    "Merman_Caught",
    "Giant Merman_Caught",
    "Fish Head_Caught",
    "Peeping Eye_Caught",
    "Peeping Big_Caught",
    "Metroid_Caught",
    "Skultera_Caught",
    "Evir_Caught",
    "Draygon_Caught",
    "Phantoon_Caught",
    "Botwoon_Caught",
    "Serris_Caught",
    "Guppy_Caught",
    "Carnivore_Caught",
    "Starcatcher_Caught",
    "Fecal Forgo_Caught",
    "Red Cheep Cheep_Caught",
    "Green Cheep Cheep_Caught",
    "Blooper_Caught",
    "Bloopad_Caught",
    "Blurp_Caught",
    "Rip Van Fish_Caught",
    "Fish Bone_Caught",
    "Morton_Caught",
    "Sonic the Fish_Caught",
    "Eggman_Caught",
    "Ring_Caught",
    "Star Post_Caught",
    "Goal Plate_Caught",
    "Item Box_Caught",
    "Spring_Caught",
    "Chopper_Caught",
    "Crabmeat_Caught",
    "Masher_Caught",
    "Chop Chop_Caught",
    "Aquis_Caught",
    "Shellcracker_Caught",
    "Asteron_Caught",
    "Turtloid_Caught",
    "Pointdexter_Caught",
    "Turbo Spiker_Caught",
    "Mega Chopper_Caught",
    "Jawz_Caught",
    "Doshin_Caught",
    "Bloppo The Warbler_Caught",
    "Octorok_Caught",
    "Big Octorok_Caught",
    "Chuchu_Caught",
    "Big Chuchu_Caught",
    "Sluggula_Caught",
    "Cloud Piranha_Caught",
    "Zora_Caught",
    "Ganondorf_Caught",
    "Atlantic Cod_Caught",
    "Neon Tetra_Caught",
    "Red Snapper_Caught",
    "Tuna_Caught",
    "Salmon_Caught",
    "Bass_Caught",
    "Flounder_Caught",
    "Rock Lobster_Caught",
    "Trout_Caught",
    "Shrimp_Caught",
    "Crimson Tigerfish_Caught",
    "Specular Fish_Caught",
    "Blue Jellyfish (Bait)_Caught",
    "Green Jellyfish (Bait)_Caught",
    "Pink Jellyfish (Bait)_Caught",
    "Stinkfish_Caught",
    "Armored Cavefish_Caught",
    "Damselfish_Caught",
    "Double Cod_Caught",
    "Ebonkoi_Caught",
    "Frost Minnow_Caught",
    "Hemopiranha_Caught",
    "Honeyfin_Caught",
    "Variegated Lardfish_Caught",
    "Obsidifish_Caught",
    "Princess Fish_Caught",
    "Flarefin Koi_Caught",
    "Prismite_Caught",
    "Golden Carp_Caught",
    "Chaos Fish_Caught",
    "Amanita Fungifin_Caught",
    "Angelfish_Caught",
    "Batfish_Caught",
    "Bloody Manowar_Caught",
    "Bonefish_Caught",
    "Bumblebee Tuna_Caught",
    "Bunnyfish_Caught",
    "Cap'n Tunabeard_Caught",
    "Catfish_Caught",
    "Cloudfish_Caught",
    "Clownfish_Caught",
    "Cursedfish_Caught",
    "Demonic Hellfish_Caught",
    "Derpfish_Caught",
    "Dirtfish_Caught",
    "Dynamite Fish_Caught",
    "Eater of Plankton_Caught",
    "Fallen Starfish_Caught",
    "Fishotron_Caught",
    "Fishron_Caught",
    "Guide Voodoo Fish_Caught",
    "Harpyfish_Caught",
    "Hungerfish_Caught",
    "Ichorfish_Caught",
    "Scabbardfish_Caught",
    "Jewelfish_Caught",
    "Mirage Fish_Caught",
    "Mudfish_Caught",
    "Mutant Flinxfin_Caught",
    "Pengfish_Caught",
    "Pixiefish_Caught",
    "Scarab Fish_Caught",
    "Scorpio Fish_Caught",
    "Slimefish_Caught",
    "Spiderfish_Caught",
    "The Fish of Cthulhu_Caught",
    "Tropical Barracuda_Caught",
    "Tundra Trout_Caught",
    "Unicorn Fish_Caught",
    "Wyverntail_Caught",
    "Zombie Fish_Caught",
    "Cheri Berry_Caught",
    "Chesto Berry_Caught",
    "Pecha Berry_Caught",
    "Rawst Berry_Caught",
    "Aspear Berry_Caught",
    "Leppa Berry_Caught",
    "Oran Berry_Caught",
    "Persim Berry_Caught",
    "Lum Berry_Caught",
    "Sitrus Berry_Caught",
    "Figy Berry_Caught",
    "Wiki Berry_Caught",
    "Mago Berry_Caught",
    "Aguav Berry_Caught",
    "Iapapa Berry_Caught",
    "Razz Berry_Caught",
    "Bluk Berry_Caught",
    "Nanab Berry_Caught",
    "Wepear Berry_Caught",
    "Pinap Berry_Caught",
    "Pomeg Berry_Caught",
    "Kelpsy Berry_Caught",
    "Qualot Berry_Caught",
    "Hondew Berry_Caught",
    "Grepa Berry_Caught",
    "Tamato Berry_Caught",
    "Cornn Berry_Caught",
    "Magost Berry_Caught",
    "Rabuta Berry_Caught",
    "Nomel Berry_Caught",
    "Spelon Berry_Caught",
    "Pamtre Berry_Caught",
    "Watmel Berry_Caught",
    "Durin Berry_Caught",
    "Belue Berry_Caught",
    "Occa Berry_Caught",
    "Passho Berry_Caught",
    "Wacan Berry_Caught",
    "Rindo Berry_Caught",
    "Yache Berry_Caught",
    "Chople Berry_Caught",
    "Kebia Berry_Caught",
    "Shuca Berry_Caught",
    "Coba Berry_Caught",
    "Payapa Berry_Caught",
    "Tanga Berry_Caught",
    "Charti Berry_Caught",
    "Kasib Berry_Caught",
    "Haban Berry_Caught",
    "Colbur Berry_Caught",
    "Babiri Berry_Caught",
    "Chilan Berry_Caught",
    "Liechi Berry_Caught",
    "Ganlon Berry_Caught",
    "Salac Berry_Caught",
    "Petaya Berry_Caught",
    "Apicot Berry_Caught",
    "Lansat Berry_Caught",
    "Starf Berry_Caught",
    "Enigma Berry_Caught",
    "Micle Berry_Caught",
    "Custap Berry_Caught",
    "Jaboca Berry_Caught",
    "Rowap Berry_Caught",
    "Roseli Berry_Caught",
    "Kee Berry_Caught",
    "Maranga Berry_Caught",
    "Chainsaw Fish_Caught",
    "7 Colored Fish_Caught",
    "Magikarp_Caught",
    "Gyrados_Caught",
    "Goldeen_Caught",
    "Seaking_Caught",
    "Horsea_Caught",
    "Seadra_Caught",
    "Kingdra_Caught",
    "Krabby_Caught",
    "Kingler_Caught",
    "Omanyte_Caught",
    "Omastar_Caught",
    "Lapras_Caught",
    "Kabuto_Caught",
    "Kabutops_Caught",
    "Tentacool_Caught",
    "Tentacruel_Caught",
    "Staryu_Caught",
    "Starmie_Caught",
    "Slowpoke_Caught",
    "Slowbro_Caught",
    "Slowking_Caught",
    "Shellder_Caught",
    "Cloyster_Caught",
    "Squirtle_Caught",
    "Wartortle_Caught",
    "Blastoise_Caught",
    "Seel_Caught",
    "Dewgong_Caught",
    "Psyduck_Caught",
    "Golduck_Caught",
    "Poliwag_Caught",
    "Poliwhirl_Caught",
    "Poliwrath_Caught",
    "Politoed_Caught",
    "Dratini_Caught",
    "Dragonair_Caught",
    "Dragonite_Caught",
    "Godzilla_Caught",
    "Rahab_Caught",
    "Plesioth_Caught",
    "Cacodemon_Caught",
    "Wolpole_Caught",
    "Water Dumple_Caught",
    "Yellow Wollyhop_Caught",
    "Toady Bloyster_Caught",
    "Puckering Blinnow_Caught",
    "Fish Taco_Caught",
    "Swedish Fish_Caught",
    "Archfiend Skull_Caught",
    "Ghost Hamster_Caught",
    "Mizzle_Caught",
    "Pluey_Caught",
    "Annoying Dogfish_Caught",
    "SPAMFISH_Caught",
    "Mr Ant Tenna_Caught",
    "Aquatic Spawn_Caught",
    "Quirky Knight_Caught",
    "Big Lenny_Caught",
    "Game Shark_Caught",
    "Gulugulugulu Wator Fish_Caught",
    "Egg Fish_Caught",
    "Ikachan_Caught",
    "Ironhead_Caught",
    "Sea-Shroom_Caught",
    "Tangle Kelp_Caught",
    "Snorkel Zombie_Caught",
    "Rotten Flesh_Caught",
    "Leather Boots_Caught",
    "Leather_Caught",
    "Bowl_Caught",
    "Stick_Caught",
    "Bone_Caught",
    "String_Caught",
    "Baggie_Caught",
    "Omni Fish_Caught",
    "Invader Squid_Caught",
    "Invader Crab_Caught",
    "Invader Octopus_Caught",
    "Invader UFO_Caught",
    "Kalamar_Caught",
    "Pipe Fiend_Caught",
    "Prey_Caught",
    "Lil' Blub_Caught",
    "Strawberry_Caught",
    "Tomato_Caught",
    "Cherries_Caught",
    "Watermelon_Caught",
    "Melon_Caught",
    "Orange_Caught",
    "Bananas_Caught",
    "Peach_Caught",
    "Carrot_Caught",
    "Green Pepper_Caught",
    "Kabocha_Caught",
    "Peas_Caught",
    "Corn_Caught",
    "Milk Carton_Caught",
    "Milk Bottle_Caught",
    "Bread_Caught",
    "Donut_Caught",
    "Pancakes_Caught",
    "Sandwich_Caught",
    "Hot Dog_Caught",
    "Burger_Caught",
    "Roast Chicken_Caught",
    "Lobster Dish_Caught",
    "Fried Eggs_Caught",
    "French Fries_Caught",
    "Cupcake_Caught",
    "Cookie_Caught",
    "Shaved Ice_Caught",
    "Ice Cream Cone_Caught",
    "Ice Cream Bar_Caught",
    "Flan_Caught",
    "Cream Soda_Caught",
    "Orange Juice_Caught",
    "Coffee_Caught",
    "Soda Can_Caught",
    "Candy Cane_Caught",
    "Candy_Caught",
    "Crepe_Caught",
    "Maxim Tomato_Caught",
    "Invincibility Candy_Caught",
    "Extra Life_Caught",
    "Treasure Chest_Caught",
    "Star Coin_Caught",
    "Gold Medal_Caught",
    "Gold Coin_Caught",
    "Whip_Caught",
    "Crystal Ball_Caught",
    "Lucky Cat_Caught",
    "Seiryu Sword_Caught",
    "Screw Attack_Caught",
    "Echigo Candy_Caught",
    "Phanto Mask_Caught",
    "Star Stone_Caught",
    "Beast Fang_Caught",
    "Bandanna_Caught",
    "Springtime_Caught",
    "Seasons Heart_Caught",
    "Dime_Caught",
    "Glass Slipper_Caught",
    "Goblet_Caught",
    "Sauce Pan_Caught",
    "Brass Knuckle_Caught",
    "Amber Rose_Caught",
    "Fish Fossil_Caught",
    "Beast Fossil_Caught",
    "Nunchucks_Caught",
    "Machine Parts_Caught",
    "Bucket_Caught",
    "Summertime_Caught",
    "Power Paintbrush_Caught",
    "100-Dollar Coin_Caught",
    "Ancient Gem_Caught",
    "Falcon Helmet_Caught",
    "Dud_Caught",
    "Cell Phone_Caught",
    "Truth Mirror_Caught",
    "Star Tiara_Caught",
    "Koopa Shell_Caught",
    "Falchion_Caught",
    "Warrior Shield_Caught",
    "Unicorn Horn_Caught",
    "Autumntime_Caught",
    "Three-Star Cane_Caught",
    "Broken Bowl_Caught",
    "Tut Mask_Caught",
    "Mr Saturn_Caught",
    "Armor_Caught",
    "Treasure Box_Caught",
    "Mannequin_Caught",
    "Gold Crown_Caught",
    "King Cape_Caught",
    "Model Ship_Caught",
    "Sun Ring_Caught",
    "Wintertime_Caught",
    "Gold Watering Can_Caught",
    "Katana_Caught",
    "Charm_Caught",
    "Xmas Tree_Caught",
    "Kong Barrel_Caught",
    "Ramia Scale_Caught",
    "Shiny Bamboo_Caught",
    "Tire_Caught",
    "Spirit Charm_Caught",
    "Pegasus Wing_Caught",
    "Raccoon Doll_Caught",
    "Shell Whistle_Caught",
    "Orichalcum_Caught",
    "Platinum Ring_Caught",
    "Triforce_Caught",
    "Crewmate_Caught",
    "Super Mushroom_Caught",
    "Soda_Caught",
    "Grape Soda_Caught",
    "Kirburger_Caught",
    "Small Silhouette Fish_Caught",
    "Silhouette Fish_Caught",
    "Big Silhouette Fish_Caught",
    "Wizzer_Caught",
    "Rango_Caught",
    "Fizzy_Caught",
    "Peeler_Caught",
    "Chubby Whale_Caught",
    "Prankler_Caught",
    "Stirfry_Caught",
    "Nozzlor_Caught",
    "Blubby_Caught",
    "Sweet Stuff_Caught",
    "Azurill_Caught",
    "Marill_Caught",
    "Azumarill_Caught",
    "Totodile_Caught",
    "Croconaw_Caught",
    "Feraligatr_Caught",
    "Chinchou_Caught",
    "Lanturn_Caught",
    "Corsola_Caught",
    "Dunsparce_Caught",
    "Mantyke_Caught",
    "Mantine_Caught",
    "Qwilfish_Caught",
    "Remoraid_Caught",
    "Octillery_Caught",
    "Wooper_Caught",
    "Quagsire_Caught",
    "Lugia_Caught",
    "Barboach_Caught",
    "Whiscash_Caught",
    "Carvana_Caught",
    "Sharpedo_Caught",
    "Clamperl_Caught",
    "Huntail_Caught",
    "Gorebyss_Caught",
    "Corphish_Caught",
    "Crawdaunt_Caught",
    "Feebas_Caught",
    "Milotic_Caught",
    "Lileep_Caught",
    "Cradily_Caught",
    "Luvdisc_Caught",
    "Mudkip_Caught",
    "Marshtomp_Caught",
    "Swampert_Caught",
    "Relicanth_Caught",
    "Spheal_Caught",
    "Sealeo_Caught",
    "Walrein_Caught",
    "Wailmer_Caught",
    "Wailord_Caught",
    "Surskit_Caught",
    "Masquerain_Caught",
    "Wingull_Caught",
    "Pelipper_Caught",
    "Kyogre_Caught",
    "Rayquaza_Caught",
    "Bidoof_Caught",
    "Bibarel_Caught",
    "Finneon_Caught",
    "Lumineon_Caught",
    "Piplup_Caught",
    "Prinplup_Caught",
    "Empoleon_Caught",
    "Shellos (West)_Caught",
    "Shellos (East)_Caught",
    "Gastrodon (West)_Caught",
    "Gastrodon (East)_Caught",
    "Phione_Caught",
    "Manaphy_Caught",
    "Forgotten Idol_Caught",
    "Gezora_Caught",
    "Hedorah_Caught",
    "Biollante Rose_Caught",
    "Biollante_Caught",
    "Varan_Caught",
    "Goomdiver_Caught",
    "Enguarde_Caught",
    "Bitesize_Caught",
    "Chomps Jr._Caught",
    "Chomps_Caught",
    "Croctopus_Caught",
    "Squidge_Caught",
    "Clambo_Caught",
    "Glimmer_Caught",
    "Clapper_Caught",
    "Flotsam_Caught",
    "Puftup_Caught",
    "Lockjaw_Caught",
    "Shuri_Caught",
    "Klaptrap_Caught",
    "Kritter_Caught",
    "Krash_Caught",
    "Klump_Caught",
    "Krusha_Caught",
    "Kudgel_Caught",
    "King K. Rool_Caught",
    "Funky Kong_Caught",
    "Duke Fishron_Caught",
    "Seadramon_Caught",
    "Trout Master Grimm_Caught",
    "Freezer_Caught",
    "Strimpfish_Caught",
    "King Fossil_Caught",
    "Great Thing_Caught",
    "Moe_Caught",
    "Old Man Lobber_Caught",
    "Starly_Caught",
    "Starfy_Caught",
    "Mine_Caught",
    "N. Trance_Caught",
    "Crash Bandicoot_Caught",
    "Dolphin_Caught",
    "Urchin_Caught",
    "Porcu-Puffer_Caught",
    "Bumpty_Caught",
    "Hootie The Blue Fish_Caught",
    "Clawdaddy_Caught",
    "Lunge Fish_Caught",
    "Prince Froggy_Caught",
    "Hookbill The Koopa_Caught",
    "Heavy Troopa_Caught",
    "Balloon Eater_Caught",
    "Karlabos_Caught",
    "Adamantoise_Caught",
    "Leviathan_Caught",
    "Toppin Cage_Caught",
    "Mushroom Toppin_Caught",
    "Tomato Toppin_Caught",
    "Sausage Toppin_Caught",
    "Pineapple Toppin_Caught",
    "Piraneapple_Caught",
    "The Doise_Caught",
    "Froggit_Caught",
    "Aaron_Caught",
    "Woshua_Caught",
    "Shyren_Caught",
    "Onion-san_Caught",
    "Undyne_Caught",
    "Cuptain_Caught",
    "Wobbly Thing_Caught",
    "Water Cooler_Caught",
    "Miss Mizzle_Caught",
    "YOUR TAKING TOO LONG_Caught",
    "Titan Spawn_Caught",
    "???_Caught",
    "DEVICE_FISH_Caught",
    "Akmodan_Caught",
    "Axe_Caught",
    "Bloodlines Count_Caught",
    "Boomerang_Caught",
    "Candle_Caught",
    "Carmilla_Caught",
    "Classic Alucard_Caught",
    "Classic Count_Caught",
    "Classic Death_Caught",
    "Classic Simon_Caught",
    "Classic Skull Knight_Caught",
    "Cross_Caught",
    "Crown_Caught",
    "Cyclops_Caught",
    "Dagger_Caught",
    "Dancing Specters_Caught",
    "Dark Count_Caught",
    "Death_Caught",
    "Double Shot_Caught",
    "Elizabeth Bartley_Caught",
    "Eric Lecarde_Caught",
    "Fire Bomb_Caught",
    "Gaibon_Caught",
    "Giant Minotaur_Caught",
    "Grant Danasty_Caught",
    "Invisibility Potion_Caught",
    "John Morris_Caught",
    "Large Heart_Caught",
    "Magic Crystal_Caught",
    "Maria Renard_Caught",
    "Moai_Caught",
    "Money Bag_Caught",
    "Morning Star_Caught",
    "Nasty Grant_Caught",
    "Phantom Bat_Caught",
    "Pork Chop_Caught",
    "Richter Belmont_Caught",
    "Slogra_Caught",
    "Small Heart_Caught",
    "Soleil Belmont_Caught",
    "Stopwatch_Caught",
    "Sypha Belnandes_Caught",
    "Torchvania_Caught",
    "Treasure Chestvania_Caught",
    "Trevor Belmont_Caught",
    "Triple Shot_Caught",
    "Undead Count_Caught",
    "Vampire Bat_Caught",
    "Zapf Bat_Caught",
    "Zombievania_Caught",
    "Dry Bones_Caught",
    "Bony Beetle_Caught",
    "Boo_Caught",
    "Silly Boo_Caught",
    "Smiling Boo_Caught",
    "Blocky Boo_Caught",
    "Eerie_Caught",
    "Big Boo_Caught",
    "Jean De Fillet_Caught",
    "Boo Guy_Caught",
    "Lantern Ghost_Caught",
    "Boolloon_Caught",
    "Blindfold Boo_Caught",
    "Spook_Caught",
    "Boo Blah_Caught",
    "King Boo_Caught",
    "Delibird_Caught",
    "Stantler_Caught",
    "Swinub_Caught",
    "Piloswine_Caught",
    "Mamoswine_Caught",
    "Sneasel_Caught",
    "Weavile_Caught",
    "Snorunt_Caught",
    "Glalie_Caught",
    "Froslass_Caught",
    "Regice_Caught",
    "Snover_Caught",
    "Abomasnow_Caught",
    "Blorbsidian_Caught",
    "Spinwulf_Caught",
    "Icedrake_Caught",
    "Tundread_Caught",
    "Rungstrider_Caught",
    "Hurlsvelgr_Caught",
    "Polar Knight_Caught",
    "Hermie III_Caught",
    "Freeze Man_Caught",
    "Frost Man_Caught",
    "Cold Man_Caught",
    "Chill Penguin_Caught",
    "Blizzard Buffalo_Caught",
    "Frost Walrus_Caught",
    "Tidal Whale_Caught",
    "Fairy Leviathan_Caught",
    "A. Phen. Leviathan_Caught",
    "Blizzack Stagroff_Caught",
    "Fenri Lunaedge_Caught",
    "Lurerre_Caught",
    "Chronoforce_Caught",
    "M. Doomsday_Caught",
    "Electoon_Caught",
    "Antitoon_Caught"
]

all_locations = fish_count_locations + fish_locations

location_table = {name: id for id, name in enumerate(all_locations, BASE_ID)}